### ISSUE TITLE
OPT: adjust docker-compose.yml  and dockerfile under unfazed.template

### ISSUE THREAD

**Issue by Provinm** [unfazed-eco/unfazed#26]
depends on `mysql` and `redis` but donot defined

```
services:
  unfazed:
    build: .
    ports:
      - "127.0.0.1:9527:9527"
    depends_on:
      - redis
      - mysql
    command: uvicorn asgi:application --host 0.0.0.0 --port 9527
    volumes:
      - .:/src


```

should delete poetry config in `dockerfile`

```
FROM python:3.12-bullseye

COPY . /src
WORKDIR /src/backend

RUN pip3 install uv
RUN poetry config virtualenvs.create false
RUN uv sync


```
